name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: chenjiyan2001/chenjiyan2001@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
